### ISSUE TITLE
question: Timespan of number of views?

### ISSUE THREAD

**Issue by agharbeia** [hatnote/top#33]
Hallo,
What does the number of views cited in the list entries represent?
Is it the number of views of the article since its creation?
Or the number of views since the article came in this top 100 list?
Or another time span?

For example the top 68th article in English Wikipedia at the time of writing this is "[Omar Khadr](https://en.wikipedia.org/wiki/Omar_Khadr)". While [its Wikipedia basic statistics page](https://en.wikipedia.org/w/index.php?title=Omar_Khadr&action=info) reports 7,320 visits between 2017/06/04 and 2017/07/03, the number cited by "top" is 33.2K views on 2017/07/04 which is its first day on this top list. Also [Wikipedia traffic statistics](https://tools.wmflabs.org/pageviews/?project=en.wikipedia.org&platform=all-access&agent=user&start=2015-07-01&end=2017-07-04&pages=Omar_Khadr) reports ٢٦٣٬٢٢٩ visits between 2015/07/01, the earliest record, and 2017/07/04.

Understanding this should help me with the [Arabic translation of the templates' strings I'm working on](https://github.com/arabdigitalexpression/top/blob/master/top/templates/strings/ar_strings.yaml), and is good to know in general.

**Comment by mahmoud** [comment]
Hello @agharbeia! The data is daily (24 hours, fetched around 1am UTC generally, as that's when the data becomes available), and uses [this API](https://wikimedia.org/api/rest_v1/#!/Pageviews_data/get_metrics_pageviews_top_project_access_year_month_day).

**Comment by agharbeia** [comment]
I had seen it, but I still cannot figure out what the numbers mean.

**Comment by slaporte** [comment]
On the Omar Khadr example, you can look up an individual article's pageviews for one day (24 hours based on UTC midnight) with [this API](https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/en.wikipedia.org/all-access/user/Omar%20Khadr/daily/20170704/20170704). The page had 33,153 views on 2017/07/04, which is [rounded and abbreviated](https://github.com/hatnote/top/blob/master/top/utils.py#L4) to 33.2K on the [Top 100 list](http://top.hatnote.com/en/wikipedia/2017/7/4.html#rank-68). There may be some slight differences with the numbers in other tools, since we show only "user" pageviews, not including some bots or spiders (according to this Wikipedia pageview API). Hope that makes sense!

I'm also looking forward to the Arabic translation.

**Comment by agharbeia** [comment]
So it is not accumulative during its existence in the top 100 list.
I see.
It makes a slight difference in how to phrase that tweet with the lest possible number of words and lest possible ambiguity.

**Comment by slaporte** [comment]
@agharbeia that's right.
