### ISSUE TITLE
Please add Hungarian top list ( https://hu.wikipedia.org/ )

### ISSUE THREAD

**Issue by zsoltika** [hatnote/top#55]
I'd love to see the Hungarian version of the list, and I'm willing to help in translating.

Shall I just fork and start translating the [templates](https://github.com/hatnote/top/tree/master/top/templates) directory, creating the `hu_` prefixed file versions? Or is it just: [https://github.com/hatnote/top/blob/master/top/templates/strings/en_strings.yaml](https://github.com/hatnote/top/blob/master/top/templates/strings/en_strings.yaml) ?

**Comment by mahmoud** [comment]
Hey @zsoltika! Glad you like it. Translating `en_strings.yaml` to a `hu_strings.yaml` would be the first and only step needed from your end. [This script](https://github.com/hatnote/top/blob/master/top/l10nize.py) generates the rest of the files. 

Been a while since we got a new localization, so it might need some dusting off. Feel free to submit the PR with the translation and we'll go from there!

**Comment by zsoltika** [comment]
Great, I just created the [pull request](https://github.com/hatnote/top/pull/56)!

**Comment by mahmoud** [comment]
And here you go! https://top.hatnote.com/hu/

Do us a favor and spread the word on the wiki so people can find out about it (maybe on [the message boards](https://hu.wikipedia.org/wiki/Wikip%C3%A9dia:%C3%9Czen%C5%91fal)?). Maybe also link it from your User page since you helped make it happen! :) Thanks again!
